#!/bin/sh

if [ -z $XDG_CURRENT_DESKTOP ]; then
    export XDG_CURRENT_DESKTOP="i3-GNOME-Flashback:GNOME-Flashback:GNOME"
fi

exec gnome-session --builtin --session=i3-gnome-flashback --disable-acceleration-check "$@"
